# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: ğŸ”¬ Research
    url: '#research'
    weight: 10
  - name: ğŸ–¥ï¸ Software
    url: '#software'
    weight: 11
  - name: ğŸ“ƒ Publications
    url: '#publication'
    weight: 12
  - name: ğŸ“° News
    url: '#news'
    weight: 20
  - name: ğŸ‘¥ Team
    url: '#people'
    weight: 30
  - name: ğŸ« Events
    url: '#event'
    weight: 40
  - name: ğŸ“¨ Contact
    url: '#contact'
    weight: 60
  - name: <i class="fa-brands fa-github"></i> GitHub
    url: '#github'
    weight: 70
  - name: <i class="fa-brands fa-twitter"></i> Twitter
    url: '#twitter'
    weight: 80
