# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: '#research'
    weight: 10
  - name:  Software
    url: '#software'
    weight: 11
  - name: Publications
    url: '#publication'
    weight: 12
  - name: News
    url: '#news'
    weight: 20
  - name: Team
    url: '#people'
    weight: 30
  - name: Events
    url: '#event'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 60
  # - name: <i class="fa-brands fa-github"></i> GitHub
  #   url: '#github'
  #   weight: 65
  - name: More
    identifier: more
    weight: 70
  - name: Collaborators
    parent: more
    url: 'collaborators'
    weight: 80
  - name: Photo
    parent: more
    url: '#photo'
    weight: 90
  # - name: <i class="fa-brands fa-github"></i> GitHub
  #   parent: more
  #   url: 'https://github.com/yewton/yewton.net'
  #   weight: 110
  # - name: <i class="fa-brands fa-twitter"></i> Twitter
  #   parent: more
  #   url: 'https://twitter.com/elonmusk?ref_src=twsrc%5Etfw'
  #   weight: 110
